<?php

namespace Database\Seeders;

use App\Enums\AgentListingStatus;
use App\Models\AgentListing;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AgentListingSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * @return array<int, array<string, mixed>>
     */
    private function agents(): array
    {
        return [
            [
                'source_url' => 'https://helloworld.a2a-samples.dev/.well-known/agent.json',
                'name' => 'Hello World Agent',
                'description' => 'A minimal A2A reference agent that returns a friendly greeting. Demonstrates streaming and extended agent card support.',
                'agent_version' => '0.0.1',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/helloworld',
                'icon_url' => null,
                'provider_name' => 'A2A Samples',
                'preferred_interface_url' => 'https://helloworld.a2a-samples.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => false,
                'supports_streaming' => true,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => true,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'A2A Samples', 'url' => 'https://a2a-samples.dev'],
                'capabilities_json' => ['streaming' => true, 'pushNotifications' => false, 'extendedAgentCard' => true],
                'supported_interfaces_json' => [['url' => 'https://helloworld.a2a-samples.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text/plain'],
                'default_output_modes_json' => ['text/plain'],
                'skills_json' => [
                    [
                        'id' => 'hello_world',
                        'name' => 'Returns hello world',
                        'description' => 'Returns a hello world greeting',
                        'tags' => ['hello world'],
                        'examples' => ['hi', 'hello world'],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['text/plain'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://currency.a2a-samples.dev/.well-known/agent.json',
                'name' => 'Currency Agent',
                'description' => 'A LangGraph-powered currency conversion agent that provides real-time exchange rates between world currencies using the Frankfurter API. Supports multi-turn dialogue and streaming responses.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/langgraph',
                'icon_url' => null,
                'provider_name' => 'A2A Samples',
                'preferred_interface_url' => 'https://currency.a2a-samples.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => false,
                'supports_streaming' => true,
                'supports_push_notifications' => true,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'A2A Samples', 'url' => 'https://a2a-samples.dev'],
                'capabilities_json' => ['streaming' => true, 'pushNotifications' => true],
                'supported_interfaces_json' => [['url' => 'https://currency.a2a-samples.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text', 'text/plain'],
                'default_output_modes_json' => ['text', 'text/plain'],
                'skills_json' => [
                    [
                        'id' => 'convert_currency',
                        'name' => 'Currency Exchange Rates Tool',
                        'description' => 'Helps with exchange values between various currencies',
                        'tags' => ['currency conversion', 'currency exchange'],
                        'examples' => ['What is exchange rate between USD and GBP?'],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['text/plain'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://currency-adk.a2a-samples.dev/.well-known/agent.json',
                'name' => 'Currency Conversion Agent',
                'description' => 'An ADK-based currency conversion agent with traceability support. Converts between currencies using live exchange rate data.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/adk_currency_agent',
                'icon_url' => null,
                'provider_name' => 'Example Org',
                'preferred_interface_url' => 'https://currency-adk.a2a-samples.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '0.3.0',
                'has_auth' => false,
                'supports_streaming' => true,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'Example Org', 'url' => 'http://example.com'],
                'capabilities_json' => ['streaming' => true],
                'supported_interfaces_json' => [['url' => 'https://currency-adk.a2a-samples.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '0.3.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text', 'text/plain', 'application/json'],
                'default_output_modes_json' => ['text', 'text/plain', 'application/json'],
                'skills_json' => [
                    [
                        'id' => 'currency_conversion',
                        'name' => 'Perform Currency Conversion',
                        'description' => 'Helps with Currency conversions',
                        'tags' => ['currency', 'conversion'],
                        'examples' => ['Helps with currency conversions'],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['text/plain'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://charts.a2a-samples.dev/.well-known/agent.json',
                'name' => 'Chart Generator Agent',
                'description' => 'Generates visualisation charts from structured CSV-like data input. Accepts tabular data and returns a rendered chart image.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/analytics',
                'icon_url' => null,
                'provider_name' => 'A2A Samples',
                'preferred_interface_url' => 'https://charts.a2a-samples.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => false,
                'supports_streaming' => false,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'A2A Samples', 'url' => 'https://a2a-samples.dev'],
                'capabilities_json' => ['streaming' => false],
                'supported_interfaces_json' => [['url' => 'https://charts.a2a-samples.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text/plain', 'text/csv'],
                'default_output_modes_json' => ['image/png', 'application/json'],
                'skills_json' => [
                    [
                        'id' => 'chart_generator',
                        'name' => 'Chart Generator',
                        'description' => 'Generate a chart based on CSV-like data passed in',
                        'tags' => ['generate image', 'edit image', 'chart', 'analytics'],
                        'examples' => ['Generate a chart of revenue: Jan,$1000 Feb,$2000 Mar,$1500'],
                        'inputModes' => ['text/plain', 'text/csv'],
                        'outputModes' => ['image/png'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://github-agent.openrouter.ai/.well-known/agent.json',
                'name' => 'GitHub Agent',
                'description' => 'Queries GitHub repositories, recent commits, and project activity using natural language. Powered by OpenRouter with streaming support.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/github-agent',
                'icon_url' => null,
                'provider_name' => 'OpenRouter',
                'preferred_interface_url' => 'https://github-agent.openrouter.ai/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => true,
                'supports_streaming' => true,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'OpenRouter', 'url' => 'https://openrouter.ai'],
                'capabilities_json' => ['streaming' => true],
                'supported_interfaces_json' => [['url' => 'https://github-agent.openrouter.ai/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => ['bearerAuth' => ['httpAuthSecurityScheme' => ['scheme' => 'Bearer']]],
                'security_requirements_json' => [['bearerAuth' => []]],
                'default_input_modes_json' => ['text'],
                'default_output_modes_json' => ['text'],
                'skills_json' => [
                    [
                        'id' => 'github_repositories',
                        'name' => 'GitHub Repositories',
                        'description' => 'Query GitHub repositories, recent updates, commits, and project activity',
                        'tags' => ['github', 'repositories', 'commits', 'code'],
                        'examples' => [
                            'Show my recent repository updates',
                            'What are the latest commits in my project?',
                            'Search for popular Python repositories with recent activity',
                        ],
                        'inputModes' => ['text'],
                        'outputModes' => ['text'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://reimbursement.google-adk.dev/.well-known/agent.json',
                'name' => 'Reimbursement Agent',
                'description' => 'Handles the employee expense reimbursement process end-to-end. Accepts reimbursement requests with amounts and business purposes, validates them, and processes approvals.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/adk_expense_reimbursement',
                'icon_url' => null,
                'provider_name' => 'Google ADK',
                'preferred_interface_url' => 'https://reimbursement.google-adk.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => true,
                'supports_streaming' => true,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'Google ADK', 'url' => 'https://google.github.io/adk-docs/'],
                'capabilities_json' => ['streaming' => true],
                'supported_interfaces_json' => [['url' => 'https://reimbursement.google-adk.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => ['bearerAuth' => ['httpAuthSecurityScheme' => ['scheme' => 'Bearer']]],
                'security_requirements_json' => [['bearerAuth' => []]],
                'default_input_modes_json' => ['text', 'text/plain'],
                'default_output_modes_json' => ['text', 'text/plain'],
                'skills_json' => [
                    [
                        'id' => 'process_reimbursement',
                        'name' => 'Process Reimbursement Tool',
                        'description' => 'Helps with the reimbursement process for users given the amount and purpose of the reimbursement.',
                        'tags' => ['reimbursement', 'expense', 'finance'],
                        'examples' => ['Can you reimburse me $20 for my lunch with the clients?'],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['text/plain'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://content-planner.google-adk.dev/.well-known/agent.json',
                'name' => 'Content Planner Agent',
                'description' => 'Creates structured outlines for content given a high-level description. Ideal for blog posts, social media content, and marketing copy.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/content_planner',
                'icon_url' => null,
                'provider_name' => 'Google ADK',
                'preferred_interface_url' => 'https://content-planner.google-adk.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => false,
                'supports_streaming' => true,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'Google ADK', 'url' => 'https://google.github.io/adk-docs/'],
                'capabilities_json' => ['streaming' => true],
                'supported_interfaces_json' => [['url' => 'https://content-planner.google-adk.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text', 'text/plain'],
                'default_output_modes_json' => ['text', 'text/plain'],
                'skills_json' => [
                    [
                        'id' => 'content_planner',
                        'name' => 'Creates outlines for content',
                        'description' => 'Creates outlines for content given a high-level description of the content',
                        'tags' => ['plan', 'outline', 'content', 'writing'],
                        'examples' => ['Create an outline for a short, upbeat, and encouraging X post about learning Java'],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['text/plain'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://travel.semantic-kernel.dev/.well-known/agent.json',
                'name' => 'SK Travel Agent',
                'description' => 'A Semantic Kernel-based travel agent providing comprehensive trip planning services including currency exchange, itinerary creation, sightseeing recommendations, dining suggestions, and event bookings.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/semantickernel',
                'icon_url' => null,
                'provider_name' => 'Microsoft Semantic Kernel',
                'preferred_interface_url' => 'https://travel.semantic-kernel.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => false,
                'supports_streaming' => true,
                'supports_push_notifications' => true,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'Microsoft Semantic Kernel', 'url' => 'https://learn.microsoft.com/en-us/semantic-kernel/'],
                'capabilities_json' => ['streaming' => true, 'pushNotifications' => true],
                'supported_interfaces_json' => [['url' => 'https://travel.semantic-kernel.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text', 'text/plain'],
                'default_output_modes_json' => ['text', 'text/plain'],
                'skills_json' => [
                    [
                        'id' => 'trip_planning_sk',
                        'name' => 'Semantic Kernel Trip Planning',
                        'description' => 'Handles comprehensive trip planning, including currency exchanges, itinerary creation, sightseeing, dining recommendations, and event bookings using Frankfurter API for currency conversions.',
                        'tags' => ['trip', 'planning', 'travel', 'currency', 'semantic-kernel'],
                        'examples' => [
                            'Plan a budget-friendly day trip to Seoul including currency exchange.',
                            "What's the exchange rate and recommended itinerary for visiting Tokyo?",
                        ],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['text/plain'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://parse-chat.llamaindex.dev/.well-known/agent.json',
                'name' => 'Parse and Chat',
                'description' => 'Parses uploaded files (PDFs, Word documents, spreadsheets) using LlamaParse and enables interactive Q&A conversations about the parsed content.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/llama_index_file_chat',
                'icon_url' => null,
                'provider_name' => 'LlamaIndex',
                'preferred_interface_url' => 'https://parse-chat.llamaindex.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => true,
                'supports_streaming' => true,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'LlamaIndex', 'url' => 'https://www.llamaindex.ai'],
                'capabilities_json' => ['streaming' => true],
                'supported_interfaces_json' => [['url' => 'https://parse-chat.llamaindex.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => ['bearerAuth' => ['httpAuthSecurityScheme' => ['scheme' => 'Bearer']]],
                'security_requirements_json' => [['bearerAuth' => []]],
                'default_input_modes_json' => ['text/plain', 'application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
                'default_output_modes_json' => ['text/plain', 'application/json'],
                'skills_json' => [
                    [
                        'id' => 'parse_and_chat',
                        'name' => 'Parse and Chat',
                        'description' => 'Parses a file and then chats with a user using the parsed content as context.',
                        'tags' => ['parse', 'chat', 'file', 'llama_parse', 'document'],
                        'examples' => ['What does this file talk about?', 'Summarize the key points in this PDF'],
                        'inputModes' => ['application/pdf', 'text/plain'],
                        'outputModes' => ['text/plain'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://veo.vertexai.google.com/.well-known/agent.json',
                'name' => 'VEO Video Generation Agent',
                'description' => "Generates high-quality videos from text prompts using Google's VEO model via Vertex AI. Provides progress updates during generation and returns a GCS link to the final video.",
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/veo_video_gen',
                'icon_url' => null,
                'provider_name' => 'Google Vertex AI',
                'preferred_interface_url' => 'https://veo.vertexai.google.com/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => true,
                'supports_streaming' => false,
                'supports_push_notifications' => true,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'Google Vertex AI', 'url' => 'https://cloud.google.com/vertex-ai'],
                'capabilities_json' => ['streaming' => false, 'pushNotifications' => true],
                'supported_interfaces_json' => [['url' => 'https://veo.vertexai.google.com/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => ['bearerAuth' => ['httpAuthSecurityScheme' => ['scheme' => 'Bearer']]],
                'security_requirements_json' => [['bearerAuth' => []]],
                'default_input_modes_json' => ['text/plain'],
                'default_output_modes_json' => ['video/mp4', 'text/plain'],
                'skills_json' => [
                    [
                        'id' => 'generate_video_from_prompt',
                        'name' => 'Generate Video from Text Prompt (VEO)',
                        'description' => 'Generates a video based on a textual description using VEO. Provides progress updates and a link to the final video.',
                        'tags' => ['video', 'generation', 'multimodal', 'veo'],
                        'examples' => [
                            'Create a video of a futuristic cityscape at sunset.',
                            'Generate a short clip of a cat playing with a yarn ball in a sunny room.',
                        ],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['video/mp4'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://movie-agent.genkit.dev/.well-known/agent.json',
                'name' => 'Movie Agent',
                'description' => 'Answers questions about movies and actors using The Movie Database (TMDB). Built with Genkit and supports multi-turn conversations and state transition history.',
                'agent_version' => '0.0.2',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/js/src/agents/movie-agent',
                'icon_url' => null,
                'provider_name' => 'A2A Samples',
                'preferred_interface_url' => 'https://movie-agent.genkit.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => false,
                'supports_streaming' => true,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'A2A Samples', 'url' => 'https://example.com/a2a-samples'],
                'capabilities_json' => ['streaming' => true, 'pushNotifications' => false, 'stateTransitionHistory' => true],
                'supported_interfaces_json' => [['url' => 'https://movie-agent.genkit.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text'],
                'default_output_modes_json' => ['text'],
                'skills_json' => [
                    [
                        'id' => 'general_movie_chat',
                        'name' => 'General Movie Chat',
                        'description' => 'Answer general questions or chat about movies, actors, directors.',
                        'tags' => ['movies', 'actors', 'directors', 'entertainment'],
                        'examples' => [
                            'Tell me about the plot of Inception.',
                            'Who directed The Godfather?',
                            'What movies has Meryl Streep appeared in recently?',
                        ],
                        'inputModes' => ['text'],
                        'outputModes' => ['text'],
                    ],
                    [
                        'id' => 'movie_search',
                        'name' => 'Movie Search',
                        'description' => 'Search for movies by title, genre, or release year using TMDB.',
                        'tags' => ['movies', 'search', 'tmdb'],
                        'examples' => ['Find action movies from 2023', 'Search for films starring Tom Hanks'],
                        'inputModes' => ['text'],
                        'outputModes' => ['text'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://coder-agent.genkit.dev/.well-known/agent.json',
                'name' => 'Coder Agent',
                'description' => 'Generates code based on natural language instructions and streams the resulting files as artifacts. Supports multiple programming languages and frameworks.',
                'agent_version' => '0.0.2',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/js/src/agents/coder',
                'icon_url' => null,
                'provider_name' => 'A2A Samples',
                'preferred_interface_url' => 'https://coder-agent.genkit.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => false,
                'supports_streaming' => true,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'A2A Samples', 'url' => 'https://example.com/a2a-samples'],
                'capabilities_json' => ['streaming' => true, 'pushNotifications' => false, 'stateTransitionHistory' => true],
                'supported_interfaces_json' => [['url' => 'https://coder-agent.genkit.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text'],
                'default_output_modes_json' => ['text', 'file'],
                'skills_json' => [
                    [
                        'id' => 'code_generation',
                        'name' => 'Code Generation',
                        'description' => 'Generates code snippets or complete files based on user requests, streaming the results.',
                        'tags' => ['code', 'development', 'programming'],
                        'examples' => [
                            'Write a python function to calculate fibonacci numbers.',
                            'Create a React component for a login form with validation.',
                        ],
                        'inputModes' => ['text'],
                        'outputModes' => ['text', 'file'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://content-editor.genkit.dev/.well-known/agent.json',
                'name' => 'Content Editor Agent',
                'description' => 'Proof-reads and polishes written content to improve clarity, grammar, and professional tone. Built with Genkit and Google Gemini.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/js/src/agents/content-editor',
                'icon_url' => null,
                'provider_name' => 'A2A Samples',
                'preferred_interface_url' => 'https://content-editor.genkit.dev/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => false,
                'supports_streaming' => true,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'A2A Samples', 'url' => 'https://example.com/a2a-samples'],
                'capabilities_json' => ['streaming' => true],
                'supported_interfaces_json' => [['url' => 'https://content-editor.genkit.dev/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text'],
                'default_output_modes_json' => ['text'],
                'skills_json' => [
                    [
                        'id' => 'editor',
                        'name' => 'Edits content',
                        'description' => 'Edits content by proof-reading and polishing',
                        'tags' => ['writing', 'editing', 'proofreading'],
                        'examples' => ['Edit the following article, make sure it has a professional tone'],
                        'inputModes' => ['text'],
                        'outputModes' => ['text'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://contact-extractor.marvin.ai/.well-known/agent.json',
                'name' => 'Marvin Contact Extractor',
                'description' => 'Interactively extracts structured contact information (name, email, phone, organization, role) from conversational text using the Marvin framework.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/marvin',
                'icon_url' => null,
                'provider_name' => 'Marvin AI',
                'preferred_interface_url' => 'https://contact-extractor.marvin.ai/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => false,
                'supports_streaming' => false,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'Marvin AI', 'url' => 'https://www.askmarvin.ai'],
                'capabilities_json' => ['streaming' => false],
                'supported_interfaces_json' => [['url' => 'https://contact-extractor.marvin.ai/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text/plain'],
                'default_output_modes_json' => ['application/json'],
                'skills_json' => [
                    [
                        'id' => 'extract_contact_info',
                        'name' => 'Extract Contact Information',
                        'description' => 'Interactively collects and extracts structured contact information from conversational input.',
                        'tags' => ['extraction', 'contact', 'structured-data', 'marvin'],
                        'examples' => [
                            "I'm Jane Smith, you can reach me at jane@acme.com or 555-0100",
                            'My name is Bob, I work at TechCorp as a software engineer',
                        ],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['application/json'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://image-gen.crewai.com/.well-known/agent.json',
                'name' => 'CrewAI Image Generator',
                'description' => 'Generates stunning, high-quality images on demand and leverages powerful editing capabilities to modify, enhance, or completely transform visuals. Built with CrewAI and Google Gemini Imagen.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/crewai',
                'icon_url' => null,
                'provider_name' => 'CrewAI',
                'preferred_interface_url' => 'https://image-gen.crewai.com/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => true,
                'supports_streaming' => false,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'CrewAI', 'url' => 'https://crewai.com'],
                'capabilities_json' => ['streaming' => false],
                'supported_interfaces_json' => [['url' => 'https://image-gen.crewai.com/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => ['bearerAuth' => ['httpAuthSecurityScheme' => ['scheme' => 'Bearer']]],
                'security_requirements_json' => [['bearerAuth' => []]],
                'default_input_modes_json' => ['text/plain'],
                'default_output_modes_json' => ['image/png', 'image/jpeg', 'text/plain'],
                'skills_json' => [
                    [
                        'id' => 'image_generator',
                        'name' => 'Image Generator',
                        'description' => 'Generate stunning, high-quality images on demand and leverage powerful editing capabilities to modify, enhance, or completely transform visuals.',
                        'tags' => ['generate image', 'edit image', 'multimodal', 'creative'],
                        'examples' => ['Generate a photorealistic image of raspberry lemonade'],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['image/png', 'image/jpeg'],
                    ],
                ],
            ],
            [
                'source_url' => 'https://airbnb-planner.ag2.ai/.well-known/agent.json',
                'name' => 'Airbnb & Weather Planner',
                'description' => 'A multi-agent orchestration demo combining Airbnb listing search with real-time weather information to help plan the perfect trip. Coordinates Airbnb and Weather sub-agents via A2A.',
                'agent_version' => '1.0.0',
                'documentation_url' => 'https://github.com/a2aproject/a2a-samples/tree/main/samples/python/agents/airbnb_planner_multiagent',
                'icon_url' => null,
                'provider_name' => 'AG2',
                'preferred_interface_url' => 'https://airbnb-planner.ag2.ai/a2a',
                'preferred_protocol_binding' => 'JSONRPC',
                'preferred_protocol_version' => '1.0',
                'has_auth' => false,
                'supports_streaming' => true,
                'supports_push_notifications' => false,
                'supports_extended_agent_card' => false,
                'status' => AgentListingStatus::Active,
                'provider_json' => ['organization' => 'AG2', 'url' => 'https://ag2.ai'],
                'capabilities_json' => ['streaming' => true],
                'supported_interfaces_json' => [['url' => 'https://airbnb-planner.ag2.ai/a2a', 'protocolBinding' => 'JSONRPC', 'protocolVersion' => '1.0']],
                'security_schemes_json' => null,
                'security_requirements_json' => null,
                'default_input_modes_json' => ['text/plain'],
                'default_output_modes_json' => ['text/plain'],
                'skills_json' => [
                    [
                        'id' => 'airbnb_search',
                        'name' => 'Airbnb Listing Search',
                        'description' => 'Search for Airbnb listings based on location, dates, and guest count',
                        'tags' => ['airbnb', 'accommodation', 'travel', 'booking'],
                        'examples' => ['Find a 2-bedroom Airbnb in Lisbon for 4 nights in July'],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['text/plain'],
                    ],
                    [
                        'id' => 'weather_forecast',
                        'name' => 'Weather Forecast',
                        'description' => 'Get real-time weather conditions and forecasts for travel destinations',
                        'tags' => ['weather', 'forecast', 'travel'],
                        'examples' => ["What's the weather like in Paris next week?"],
                        'inputModes' => ['text/plain'],
                        'outputModes' => ['text/plain'],
                    ],
                ],
            ],
        ];
    }

    public function run(): void
    {
        foreach ($this->agents() as $data) {
            $rawCard = [
                'name' => $data['name'],
                'description' => $data['description'],
                'version' => $data['agent_version'],
                'documentationUrl' => $data['documentation_url'],
                'provider' => $data['provider_json'],
                'capabilities' => $data['capabilities_json'],
                'supportedInterfaces' => $data['supported_interfaces_json'],
                'defaultInputModes' => $data['default_input_modes_json'],
                'defaultOutputModes' => $data['default_output_modes_json'],
                'skills' => $data['skills_json'],
            ];

            if ($data['security_schemes_json']) {
                $rawCard['securitySchemes'] = $data['security_schemes_json'];
                $rawCard['securityRequirements'] = $data['security_requirements_json'];
            }

            $searchDocument = implode(' ', array_filter([
                $data['name'],
                $data['description'],
                $data['provider_name'],
                ...array_column($data['skills_json'], 'name'),
                ...array_column($data['skills_json'], 'description'),
                ...array_merge(...array_column($data['skills_json'], 'tags')),
            ]));

            AgentListing::create([
                ...$data,
                'search_document' => $searchDocument,
                'raw_card_json' => $rawCard,
                'signatures_json' => null,
                'validation_warnings_json' => [],
                'etag' => hash('sha1', $data['source_url']),
                'last_modified' => 'Wed, 22 Apr 2026 12:00:00 GMT',
                'content_type' => 'application/json',
                'content_hash' => hash('sha256', json_encode($rawCard, JSON_THROW_ON_ERROR)),
                'last_http_status' => 200,
                'last_error' => null,
                'fetched_at' => now(),
                'validated_at' => now(),
                'refresh_due_at' => now()->addDay(),
            ]);
        }
    }
}
